version: "2"

services:
  docs:
    build: .
    volumes:
      - .:/docs
    working_dir: /docs
    ports:
      - 8000:8000
    entrypoint: mkdocs
    command:
      - serve
      - --livereload
      - --dev-addr=0.0.0.0:8000
