repo_name: ilyasotkov/high-level-devops
repo_url: https://github.com/ilyasotkov/high-level-devops
edit_uri: ""

pages:
  - Overview: index.md

copyright: 'Copyright &copy; 2018 Ilya Sotkov'

docs_dir: 'docs'
extra_css:
  - 'css/extra.css'
markdown_extensions:
  - codehilite:
      linenums: false
  - admonition
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
theme:
  name: material
  custom_dir: _docs/theme
  logo:
    icon: cloud_upload
  feature:
    tabs: true
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    primary: green
    accent: green
site_name: High-level DevOps
